---

- hosts: all
  name: Install Roles
  pre_tasks:
    - name: Remove stale BSDINSTALL_DISTDIR
      file:
        path: /usr/freebsd-dist
        state: absent
      become: yes
  roles:
    #    - update
    #    - ocluster
    #    - docker
    - { role: base-image, version: "busybox", user_name: opam, zfs_pool: "obuilder", default: false }
    - { role: base-image, version: "4.14.4", user_name: opam, zfs_pool: "obuilder" , default: false }
    - { role: base-image, version: "5.5.0", user_name: opam, zfs_pool: "obuilder" , default: true }

